# Generated by Django 4.2.7 on 2024-01-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='I am happy to use Fitiness , I can only recommend it to you', max_length=500),
        ),
    ]
