# Generated by Django 4.2.7 on 2024-01-14 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0003_alter_wishlist_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
