#######
#Just an example, needs to be adjusted 
#######
version: '3'

services:
  frontend:
    build: ./Frontend
    ports:
      - "8080:8080"
#author: Sarish
    volumes:
      - ./Frontend:/app:delegated
      - /app/node_modules
    depends_on:
      - api
#author: Sarish
#co-author: Arsselan
  api:
    container_name: django
    build: ./django-docker
    ports:
      - "8000:8000"
    command: bash -c "python manage.py generate_dummyProduct && python manage.py runserver_plus --cert-file localhost.pem --key-file localhost-key.pem"

              
    volumes:
      - ./django-docker:/code
    depends_on:
      - db
#author: Sarish
  db:
    container_name: db
    build: ./postgres-tls-certs
    #image: postgres:16.1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      #POSTGRES_INITDB_ARGS: -c ssl=on -c ssl_cert_file=/certificates/server.crt -c ssl_key_file=/certificates/server.key
    
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    volumes:
      - ./postgres-tls-certs:/certificates
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data:
